WIKI_LANGUAGE_REGION = {
    "enwiki":  {"language": "English","region": "Global / Anglosphere"},
    "simplewiki": {"language": "Simple English", "region": "Global"},
    "dewiki":  {"language": "German",      "region": "Germany / DACH"},
    "frwiki":  {"language": "French",      "region": "France / Francophone"},
    "eswiki":  {"language": "Spanish",     "region": "Spain / Latin America"},
    "itwiki":  {"language": "Italian",     "region": "Italy"},
    "jawiki":  {"language": "Japanese",    "region": "Japan"},
    "zhwiki":  {"language": "Chinese",     "region": "China / Taiwan / Singapore"},
    "arwiki":  {"language": "Arabic",      "region": "Middle East / North Africa"},
    "ruwiki":  {"language": "Russian",     "region": "Russia / CIS"},
    "ptwiki":  {"language": "Portuguese",  "region": "Portugal / Brazil"},
    "nlwiki":  {"language": "Dutch",       "region": "Netherlands / Belgium"},
    "svwiki":  {"language": "Swedish",     "region": "Sweden"},
    "plwiki":  {"language": "Polish",      "region": "Poland"},
    "cswiki":  {"language": "Czech",       "region": "Czech Republic"},
    "ukwiki":  {"language": "Ukrainian",   "region": "Ukraine"},
    "hewiki":  {"language": "Hebrew",      "region": "Israel"},
    "kowiki":  {"language": "Korean",      "region": "South Korea"},
    "viwiki":  {"language": "Vietnamese",  "region": "Vietnam"},
    "idwiki": {"language": "Indonesian", "region": "Indonesia"}, 
    "fawiki": {"language": "Persian", "region": "Iran / Afghanistan / Tajikistan"}, 
    "trwiki": {"language": "Turkish", "region": "Turkey"}, 
    "huwiki": {"language": "Hungarian", "region": "Hungary"}, 
    "rowiki": {"language": "Romanian", "region": "Romania / Moldova"}, 
    "fiwiki": {"language": "Finnish", "region": "Finland"}, 
    "nowiki": {"language": "Norwegian", "region": "Norway"}, 
    "elwiki": {"language": "Greek", "region": "Greece / Cyprus"}, 
    "bgwiki": {"language": "Bulgarian", "region": "Bulgaria"}, 
    "thwiki": {"language": "Thai", "region": "Thailand"}, 
    "bnwiki": {"language": "Bengali", "region": "Bangladesh / India"}, 
    "hiwiki": {"language": "Hindi", "region": "India"}, 
    "urwiki": {"language": "Urdu", "region": "Pakistan"}, 
    "etwiki": {"language": "Estonian", "region": "Estonia"}, 
    "ltwiki": {"language": "Lithuanian", "region": "Lithuania"}, 
    "lvwiki": {"language": "Latvian", "region": "Latvia"}
}
